module.exports = function generateSwift(hyperschema) {
  const lines = [
    '// This file is autogenerated by the hyperschema compiler',
    '// !!DO NOT EDIT THIS FILE!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    'import CompactEncoding',
    'import Foundation',
    '',
    'public func encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {',
    '  var state = State()',
    '  codec.preencode(&state, value)',
    '  state.allocate()',
    '  try codec.encode(&state, value)',
    '  return state.buffer',
    '}',
    '',
    'public func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {',
    '  var state = State(data)',
    '  return try codec.decode(&state)',
    '}'
  ]

  // An unknown enum tag or schema version is a recoverable decode failure, not
  // a reason to crash: a peer can legitimately send a newer variant or version.
  // Emitted only when there is something that can hit it.
  if (hyperschema.schema.some((_, i) => isThrowingTagType(hyperschema, i))) {
    lines.push(
      '',
      'public enum SchemaDecodeError: Error {',
      '  case unknownEnumVariant(type: String, tag: UInt)',
      '  case unknownVersion(type: String, version: UInt)',
      '}'
    )
  }

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (type.isEnum) {
      lines.push('', ...generateEnum(type))
    } else if (type.isStruct) {
      lines.push('', ...generateStruct(type))
      if (type.isInlined) lines.push('', ...generateStructCodec(type, 'inline'))
    } else if (type.isArray) {
      lines.push('', ...generateArray(type))
    } else if (type.isRecord) {
      lines.push('', ...generateRecord(type))
    } else if (type.isVersioned) {
      lines.push('', ...generateVersioned(type))
    }
  }

  return lines.join('\n') + '\n'
}

// Whether the type at schema position `i` decodes a tag that can be unknown
// (an enum variant or a versioned dispatch), and so needs SchemaDecodeError.
function isThrowingTagType(hyperschema, i) {
  const type = hyperschema.resolve(hyperschema.typesByPosition.get(i))
  return type.isEnum || type.isVersioned
}

function toSwiftTypeName(name) {
  return name
    .split('-')
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join('')
}

function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

// Swift reserved words that are invalid as a bare identifier. A schema name
// that collides with one (a field called `default`, a type called `class`)
// would otherwise emit uncompilable Swift, so it is backtick-escaped. This
// changes only the surfaced identifier — never the codec var names (which are
// underscore-prefixed and so always safe) nor the wire format.
const SWIFT_KEYWORDS = new Set([
  'associatedtype',
  'class',
  'deinit',
  'enum',
  'extension',
  'fileprivate',
  'func',
  'import',
  'init',
  'inout',
  'internal',
  'let',
  'open',
  'operator',
  'private',
  'precedencegroup',
  'protocol',
  'public',
  'rethrows',
  'static',
  'struct',
  'subscript',
  'typealias',
  'var',
  'break',
  'case',
  'catch',
  'continue',
  'default',
  'defer',
  'do',
  'else',
  'fallthrough',
  'for',
  'guard',
  'if',
  'in',
  'repeat',
  'return',
  'switch',
  'throw',
  'where',
  'while',
  'as',
  'await',
  'Any',
  'false',
  'is',
  'nil',
  'self',
  'Self',
  'super',
  'throws',
  'true',
  'try'
])

function swiftIdent(name) {
  return SWIFT_KEYWORDS.has(name) ? '`' + name + '`' : name
}

function resolveBaseType(type) {
  if (type.isAlias) return resolveBaseType(type.type)
  return type
}

// Swift mapping for each compact-encoding primitive. The codec var is always
// '_' + name, so it is derived rather than stored. `swift` (the Swift value
// type) and `init` (the codec constructor) don't follow a rule — e.g. string
// uses Primitive.UTF8(), buffer uses Data — so they are spelled out.
const PRIMITIVES = {
  uint: { swift: 'UInt', init: 'Primitive.UInt()' },
  uint8: { swift: 'UInt8', init: 'Primitive.UInt8()' },
  uint16: { swift: 'UInt16', init: 'Primitive.UInt16()' },
  uint32: { swift: 'UInt32', init: 'Primitive.UInt32()' },
  int: { swift: 'Int', init: 'Primitive.Int()' },
  float32: { swift: 'Float', init: 'Primitive.Float32()' },
  float64: { swift: 'Double', init: 'Primitive.Float64()' },
  bool: { swift: 'Bool', init: 'Primitive.Bool()' },
  string: { swift: 'String', init: 'Primitive.UTF8()' },
  buffer: { swift: 'Data', init: 'Primitive.Buffer()' },
  json: { swift: 'Any', init: 'Primitive.JSON()' }
}

function getSwiftType(type) {
  const base = resolveBaseType(type)
  const prim = PRIMITIVES[base.name]
  if (prim) return prim.swift
  if (base.isEnum || base.isStruct) return swiftIdent(toSwiftTypeName(base.name))
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecVar(type) {
  const base = resolveBaseType(type)
  if (PRIMITIVES[base.name]) return '_' + base.name
  if (base.isEnum) return '_' + toSwiftInstanceName(base.name)
  if (base.isStruct) {
    const prefix = base.compact ? '_' : '_framed_'
    return prefix + toSwiftInstanceName(base.name)
  }
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecInit(type) {
  const base = resolveBaseType(type)
  const prim = PRIMITIVES[base.name]
  if (prim) return prim.init
  if (base.isEnum) return toSwiftTypeName(base.name) + 'Codec()'
  if (base.isStruct) {
    const inner = toSwiftTypeName(base.name) + 'Codec()'
    return base.compact ? inner : `Primitive.Frame(${inner})`
  }
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getFieldCodecVar(field) {
  if (field.array) return '_array_' + field.name
  if (field.inline) return '_' + toSwiftInstanceName(field.type.name) + 'Inline'
  return getSwiftCodecVar(field.type)
}

function fieldSwiftType(field) {
  if (isBoolField(field)) return 'Bool'
  const base = getSwiftType(field.type)
  if (field.array) return isOptionalField(field) ? `[${base}]?` : `[${base}]`
  return isOptionalField(field) ? `${base}?` : base
}

function isBoolField(field) {
  return field.type && field.type.bool
}

function isOptionalField(field) {
  return field.flag > 0 && !isBoolField(field)
}

function generateEnum(type) {
  const typeName = toSwiftTypeName(type.name)
  const safeType = swiftIdent(typeName)
  const safeInstance = swiftIdent(toSwiftInstanceName(type.name))
  const variants = type.enum
  const offset = type.offset || 0

  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`public enum ${safeType} {`)
  for (const v of variants) {
    lines.push(`  case ${swiftIdent(v.key)}`)
  }
  lines.push('}')
  lines.push('')

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${safeType}`)
  lines.push('')
  lines.push(`  let _uint = Primitive.UInt()`)
  lines.push('')
  lines.push(`  public init() {}`)
  lines.push('')

  // preencode and encode differ only by the verb and the `try` prefix
  for (const [fn, tryKw] of [
    ['preencode', ''],
    ['encode', 'try ']
  ]) {
    const throws = fn === 'encode' ? ' throws' : ''
    lines.push(`  public func ${fn}(_ state: inout State, _ value: ${safeType})${throws} {`)
    lines.push(`    switch value {`)
    for (let i = 0; i < variants.length; i++) {
      lines.push(
        `    case .${swiftIdent(variants[i].key)}: ${tryKw}_uint.${fn}(&state, ${offset + i})`
      )
    }
    lines.push(`    }`)
    lines.push(`  }`)
    lines.push('')
  }

  lines.push(`  public func decode(_ state: inout State) throws -> ${safeType} {`)
  lines.push(`    let tag = try _uint.decode(&state)`)
  lines.push(`    switch tag {`)
  for (let i = 0; i < variants.length; i++) {
    lines.push(`    case ${offset + i}: return .${swiftIdent(variants[i].key)}`)
  }
  lines.push(
    `    default: throw SchemaDecodeError.unknownEnumVariant(type: "${typeName}", tag: tag)`
  )
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push('')

  lines.push(`public let ${safeInstance} = ${typeName}Codec()`)

  return lines
}

function generateVersioned(type) {
  const typeName = toSwiftTypeName(type.name)
  const safeType = swiftIdent(typeName)
  const safeInstance = swiftIdent(toSwiftInstanceName(type.name))
  const versions = type.versions

  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`public enum ${safeType} {`)
  for (const v of versions) {
    lines.push(`  case v${v.version}(${swiftIdent(toSwiftTypeName(v.type.name))})`)
  }
  lines.push('}')
  lines.push('')

  // Collect unique codec variables (multiple version numbers may share one sub-type)
  const codecVars = new Map()
  for (const v of versions) {
    const varName = '_' + toSwiftInstanceName(v.type.name)
    if (!codecVars.has(varName)) {
      codecVars.set(varName, toSwiftTypeName(v.type.name) + 'Codec()')
    }
  }

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${safeType}`)
  lines.push('')
  lines.push(`  let _uint = Primitive.UInt()`)
  for (const [varName, init] of codecVars) {
    lines.push(`  let ${varName} = ${init}`)
  }
  lines.push('')
  lines.push(`  public init() {}`)
  lines.push('')

  // preencode and encode differ only by the verb and the `try` prefix
  for (const [fn, tryKw] of [
    ['preencode', ''],
    ['encode', 'try ']
  ]) {
    const throws = fn === 'encode' ? ' throws' : ''
    lines.push(`  public func ${fn}(_ state: inout State, _ value: ${safeType})${throws} {`)
    lines.push(`    switch value {`)
    for (const v of versions) {
      const varName = '_' + toSwiftInstanceName(v.type.name)
      lines.push(`    case .v${v.version}(let m):`)
      lines.push(`      ${tryKw}_uint.${fn}(&state, m.version)`)
      lines.push(`      ${tryKw}${varName}.${fn}(&state, m)`)
    }
    lines.push(`    }`)
    lines.push(`  }`)
    lines.push('')
  }

  lines.push(`  public func decode(_ state: inout State) throws -> ${safeType} {`)
  lines.push(`    let v = try _uint.decode(&state)`)
  lines.push(`    switch v {`)
  let prevVersion = -1
  for (const ver of versions) {
    const varName = '_' + toSwiftInstanceName(ver.type.name)
    const lo = prevVersion + 1
    const hi = ver.version
    const range = lo === hi ? String(lo) : `${lo}...${hi}`
    lines.push(`    case ${range}: return .v${ver.version}(try ${varName}.decode(&state))`)
    prevVersion = ver.version
  }
  lines.push(`    default: throw SchemaDecodeError.unknownVersion(type: "${typeName}", version: v)`)
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push('')
  lines.push(`public let ${safeInstance} = ${typeName}Codec()`)

  return lines
}

function generateArray(type) {
  const safeInstance = swiftIdent(toSwiftInstanceName(type.name))
  const elementCodecInit = getSwiftCodecInit(type.type)

  const lines = []
  lines.push(`// ${type.fqn}`)
  lines.push(`public let ${safeInstance} = Primitive.Array(${elementCodecInit})`)
  return lines
}

function generateRecord(type) {
  const safeInstance = swiftIdent(toSwiftInstanceName(type.name))
  const valueCodecInit = getSwiftCodecInit(type.value)

  const lines = []
  lines.push(`// ${type.fqn}`)
  lines.push(`public let ${safeInstance} = Primitive.Record(${valueCodecInit})`)
  return lines
}

// Emits the value type (fields + memberwise init) plus its standard codec.
function generateStruct(struct) {
  return [...generateStructType(struct), '', ...generateStructCodec(struct, 'standard')]
}

function generateStructType(struct) {
  const safeType = swiftIdent(toSwiftTypeName(struct.name))
  const fields = struct.fields

  const lines = []
  lines.push(`// ${struct.fqn}`)
  lines.push(`public struct ${safeType} {`)
  for (const field of fields) {
    lines.push(`  public var ${swiftIdent(field.name)}: ${fieldSwiftType(field)}`)
  }
  lines.push('')
  const initParams = fields.map((f) => {
    if (isBoolField(f)) return `${swiftIdent(f.name)}: Bool = false`
    if (isOptionalField(f)) return `${swiftIdent(f.name)}: ${fieldSwiftType(f)} = nil`
    return `${swiftIdent(f.name)}: ${fieldSwiftType(f)}`
  })
  lines.push(`  public init(${initParams.join(', ')}) {`)
  for (const field of fields) {
    lines.push(`    self.${swiftIdent(field.name)} = ${swiftIdent(field.name)}`)
  }
  lines.push('  }')
  lines.push('}')
  return lines
}

// Emits a struct's codec. mode === 'standard' produces the top-level Codec
// conformance that owns the flags word; mode === 'inline' produces the inline
// codec whose flags are supplied by the enclosing struct via `inlining`.
function generateStructCodec(struct, mode) {
  const inline = mode === 'inline'
  const typeName = toSwiftTypeName(struct.name)
  const safeType = swiftIdent(typeName)
  const codecName = typeName + (inline ? 'InlineCodec' : 'Codec')
  const safeInstance = swiftIdent(toSwiftInstanceName(struct.name) + (inline ? 'Inline' : ''))
  const fields = struct.fields
  const flagsPosition = struct.flagsPosition
  const hasFlags = flagsPosition !== -1
  const preEnd = hasFlags ? flagsPosition : fields.length

  // The one knob behind the var-name divergence: the standard codec keeps
  // per-field vars (arrays, nested inline codecs); the inline codec keys off
  // the field's plain type codec.
  const codecVar = inline ? (f) => getSwiftCodecVar(f.type) : (f) => getFieldCodecVar(f)

  const shiftByField = new Map()
  for (const rf of struct.resolvedFields || []) {
    shiftByField.set(rf.field.name, rf.shift)
  }

  // _uint backs the flags word (standard codec only); bool fields need no codec
  const codecs = new Map()
  if (hasFlags && !inline) codecs.set('_uint', 'Primitive.UInt()')
  for (const field of fields) {
    if (isBoolField(field)) continue
    const varName = codecVar(field)
    if (codecs.has(varName)) continue
    let init
    if (field.array) {
      init = 'Primitive.Array(' + getSwiftCodecInit(field.type) + ')'
    } else if (!inline && field.inline) {
      init = toSwiftTypeName(field.type.name) + 'InlineCodec()'
    } else {
      init = getSwiftCodecInit(field.type)
    }
    codecs.set(varName, init)
  }

  const lines = []
  // The standard codec shares the value type's leading comment; the inline
  // codec gets its own so it is distinguishable in the output.
  if (inline) lines.push(`// ${struct.fqn} (inline)`)
  lines.push(`public struct ${codecName}${inline ? '' : ': Codec'} {`)
  if (!inline) {
    lines.push(`  public typealias Value = ${safeType}`)
    lines.push('')
  }
  for (const [varName, init] of codecs) {
    lines.push(`  let ${varName} = ${init}`)
  }
  lines.push('')
  if (!inline) {
    lines.push(`  public init() {}`)
    lines.push('')
  }

  // preencode and encode are identical bar the verb and the `try` prefix.
  for (const [fn, tryKw] of [
    ['preencode', ''],
    ['encode', 'try ']
  ]) {
    const throws = fn === 'encode' ? ' throws' : ''
    lines.push(`  public func ${fn}(_ state: inout State, _ value: ${safeType})${throws} {`)
    for (let i = 0; i < preEnd; i++) {
      const f = fields[i]
      lines.push(`    ${tryKw}${codecVar(f)}.${fn}(&state, value.${swiftIdent(f.name)})`)
    }
    if (hasFlags) {
      if (!inline) {
        lines.push(`    var _flags: UInt = 0`)
        for (let i = flagsPosition; i < fields.length; i++) {
          const f = fields[i]
          if (isBoolField(f))
            lines.push(`    if value.${swiftIdent(f.name)} { _flags |= ${f.flag} }`)
          else if (isOptionalField(f))
            lines.push(`    if value.${swiftIdent(f.name)} != nil { _flags |= ${f.flag} }`)
        }
        lines.push(`    ${tryKw}_uint.${fn}(&state, _flags)`)
      }
      for (let i = flagsPosition; i < fields.length; i++) {
        const f = fields[i]
        if (isBoolField(f)) continue
        if (isOptionalField(f)) {
          lines.push(
            `    if let _v = value.${swiftIdent(f.name)} { ${tryKw}${codecVar(f)}.${fn}(&state, _v) }`
          )
        } else {
          lines.push(`    ${tryKw}${codecVar(f)}.${fn}(&state, value.${swiftIdent(f.name)})`)
        }
      }
    }
    lines.push('  }')
    lines.push('')
  }

  lines.push(
    inline
      ? `  public func decode(_ state: inout State, inlining: UInt) throws -> ${safeType} {`
      : `  public func decode(_ state: inout State) throws -> ${safeType} {`
  )
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`    let ${swiftIdent(f.name)} = try ${codecVar(f)}.decode(&state)`)
  }
  if (hasFlags) {
    const flags = inline ? 'inlining' : '_flags'
    if (!inline) lines.push(`    let _flags = try _uint.decode(&state)`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) {
        lines.push(`    let ${swiftIdent(f.name)} = ${flags} & ${f.flag} != 0`)
      } else if (isOptionalField(f)) {
        if (!inline && f.inline) {
          const shift = shiftByField.get(f.name) || 0
          lines.push(
            `    let ${swiftIdent(f.name)}: ${fieldSwiftType(f)} = ${flags} & ${f.flag} != 0 ? try ${codecVar(f)}.decode(&state, inlining: ${flags} >> ${shift}) : nil`
          )
        } else {
          lines.push(
            `    let ${swiftIdent(f.name)}: ${fieldSwiftType(f)} = ${flags} & ${f.flag} != 0 ? try ${codecVar(f)}.decode(&state) : nil`
          )
        }
      } else {
        lines.push(`    let ${swiftIdent(f.name)} = try ${codecVar(f)}.decode(&state)`)
      }
    }
  }
  lines.push(`    return ${safeType}(`)
  for (let i = 0; i < fields.length; i++) {
    const comma = i < fields.length - 1 ? ',' : ''
    lines.push(`      ${swiftIdent(fields[i].name)}: ${swiftIdent(fields[i].name)}${comma}`)
  }
  lines.push('    )')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push(`public let ${safeInstance} = ${codecName}()`)

  return lines
}
