module.exports = function generateSwift(hyperschema) {
  const lines = [
    '// This file is autogenerated by the hyperschema compiler',
    '// !!DO NOT EDIT THIS FILE!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    'import CompactEncoding',
    'import Foundation',
    '',
    'public func encode<C: Codec>(_ codec: C, _ value: C.Value) -> Data {',
    '  var state = State()',
    '  codec.preencode(&state, value)',
    '  state.allocate()',
    '  try! codec.encode(&state, value)',
    '  return state.buffer',
    '}',
    '',
    'public func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {',
    '  var state = State(data)',
    '  return try codec.decode(&state)',
    '}'
  ]

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (type.isEnum) {
      lines.push('', ...generateEnum(type))
    } else if (type.isStruct) {
      lines.push('', ...generateStruct(type))
      if (type.isInlined) lines.push('', ...generateInlineCodec(type))
    } else if (type.isArray) {
      lines.push('', ...generateArray(type))
    } else if (type.isRecord) {
      lines.push('', ...generateRecord(type))
    } else if (type.isVersioned) {
      lines.push('', ...generateVersioned(type))
    }
  }

  return lines.join('\n') + '\n'
}

function toSwiftTypeName(name) {
  return name
    .split('-')
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join('')
}

function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

function resolveBaseType(type) {
  if (type.isAlias) return resolveBaseType(type.type)
  return type
}

function getSwiftType(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'UInt'
  if (base.name === 'uint8') return 'UInt8'
  if (base.name === 'uint16') return 'UInt16'
  if (base.name === 'uint32') return 'UInt32'
  if (base.name === 'int') return 'Int'
  if (base.name === 'float32') return 'Float'
  if (base.name === 'float64') return 'Double'
  if (base.name === 'bool') return 'Bool'
  if (base.name === 'string') return 'String'
  if (base.name === 'buffer') return 'Data'
  if (base.isEnum) return toSwiftTypeName(base.name)
  if (base.isStruct) return toSwiftTypeName(base.name)
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecVar(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return '_uint'
  if (base.name === 'uint8') return '_uint8'
  if (base.name === 'uint16') return '_uint16'
  if (base.name === 'uint32') return '_uint32'
  if (base.name === 'int') return '_int'
  if (base.name === 'float32') return '_float32'
  if (base.name === 'float64') return '_float64'
  if (base.name === 'bool') return '_bool'
  if (base.name === 'string') return '_string'
  if (base.name === 'buffer') return '_buffer'
  if (base.isEnum) return '_' + toSwiftInstanceName(base.name)
  if (base.isStruct) {
    const prefix = base.compact ? '_' : '_framed_'
    return prefix + toSwiftInstanceName(base.name)
  }
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecInit(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'Primitive.UInt()'
  if (base.name === 'uint8') return 'Primitive.UInt8()'
  if (base.name === 'uint16') return 'Primitive.UInt16()'
  if (base.name === 'uint32') return 'Primitive.UInt32()'
  if (base.name === 'int') return 'Primitive.Int()'
  if (base.name === 'float32') return 'Primitive.Float32()'
  if (base.name === 'float64') return 'Primitive.Float64()'
  if (base.name === 'bool') return 'Primitive.Bool()'
  if (base.name === 'string') return 'Primitive.UTF8()'
  if (base.name === 'buffer') return 'Primitive.Buffer()'
  if (base.isEnum) return toSwiftTypeName(base.name) + 'Codec()'
  if (base.isStruct) {
    const inner = toSwiftTypeName(base.name) + 'Codec()'
    return base.compact ? inner : `Primitive.Frame(${inner})`
  }
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getFieldSwiftType(field) {
  const base = getSwiftType(field.type)
  return field.array ? `[${base}]` : base
}

function getFieldCodecVar(field) {
  if (field.array) return '_array_' + field.name
  if (field.inline) return '_' + toSwiftInstanceName(field.type.name) + 'Inline'
  return getSwiftCodecVar(field.type)
}

function isBoolField(field) {
  return field.type && field.type.bool
}

function isOptionalField(field) {
  return field.flag > 0 && !isBoolField(field)
}

function generateEnum(type) {
  const typeName = toSwiftTypeName(type.name)
  const instanceName = toSwiftInstanceName(type.name)
  const variants = type.enum
  const offset = type.offset || 0

  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`public enum ${typeName} {`)
  for (const v of variants) {
    lines.push(`  case ${v.key}`)
  }
  lines.push('}')
  lines.push('')

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${typeName}`)
  lines.push('')
  lines.push(`  let _uint = Primitive.UInt()`)
  lines.push('')
  lines.push(`  public init() {}`)
  lines.push('')

  lines.push(`  public func preencode(_ state: inout State, _ value: ${typeName}) {`)
  lines.push(`    switch value {`)
  for (let i = 0; i < variants.length; i++) {
    lines.push(`    case .${variants[i].key}: _uint.preencode(&state, ${offset + i})`)
  }
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push('')

  lines.push(`  public func encode(_ state: inout State, _ value: ${typeName}) throws {`)
  lines.push(`    switch value {`)
  for (let i = 0; i < variants.length; i++) {
    lines.push(`    case .${variants[i].key}: try _uint.encode(&state, ${offset + i})`)
  }
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push('')

  lines.push(`  public func decode(_ state: inout State) throws -> ${typeName} {`)
  lines.push(`    switch try _uint.decode(&state) {`)
  for (let i = 0; i < variants.length; i++) {
    lines.push(`    case ${offset + i}: return .${variants[i].key}`)
  }
  lines.push(`    default: fatalError("unknown ${typeName} variant")`)
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push('')

  lines.push(`public let ${instanceName} = ${typeName}Codec()`)

  return lines
}

function generateVersioned(type) {
  const typeName = toSwiftTypeName(type.name)
  const instanceName = toSwiftInstanceName(type.name)
  const versions = type.versions

  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`public enum ${typeName} {`)
  for (const v of versions) {
    lines.push(`  case v${v.version}(${toSwiftTypeName(v.type.name)})`)
  }
  lines.push('}')
  lines.push('')

  // Collect unique codec variables (multiple version numbers may share one sub-type)
  const codecVars = new Map()
  for (const v of versions) {
    const varName = '_' + toSwiftInstanceName(v.type.name)
    if (!codecVars.has(varName)) {
      codecVars.set(varName, toSwiftTypeName(v.type.name) + 'Codec()')
    }
  }

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${typeName}`)
  lines.push('')
  lines.push(`  let _uint = Primitive.UInt()`)
  for (const [varName, init] of codecVars) {
    lines.push(`  let ${varName} = ${init}`)
  }
  lines.push('')
  lines.push(`  public init() {}`)
  lines.push('')

  lines.push(`  public func preencode(_ state: inout State, _ value: ${typeName}) {`)
  lines.push(`    switch value {`)
  for (const v of versions) {
    const varName = '_' + toSwiftInstanceName(v.type.name)
    lines.push(`    case .v${v.version}(let m):`)
    lines.push(`      _uint.preencode(&state, m.version)`)
    lines.push(`      ${varName}.preencode(&state, m)`)
  }
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push('')

  lines.push(`  public func encode(_ state: inout State, _ value: ${typeName}) throws {`)
  lines.push(`    switch value {`)
  for (const v of versions) {
    const varName = '_' + toSwiftInstanceName(v.type.name)
    lines.push(`    case .v${v.version}(let m):`)
    lines.push(`      try _uint.encode(&state, m.version)`)
    lines.push(`      try ${varName}.encode(&state, m)`)
  }
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push('')

  lines.push(`  public func decode(_ state: inout State) throws -> ${typeName} {`)
  lines.push(`    let v = try _uint.decode(&state)`)
  lines.push(`    switch v {`)
  let prevVersion = -1
  for (const ver of versions) {
    const varName = '_' + toSwiftInstanceName(ver.type.name)
    const lo = prevVersion + 1
    const hi = ver.version
    const range = lo === hi ? String(lo) : `${lo}...${hi}`
    lines.push(`    case ${range}: return .v${ver.version}(try ${varName}.decode(&state))`)
    prevVersion = ver.version
  }
  lines.push(`    default: fatalError("unknown ${typeName} version \\(v)")`)
  lines.push(`    }`)
  lines.push(`  }`)
  lines.push(`}`)
  lines.push('')
  lines.push(`public let ${instanceName} = ${typeName}Codec()`)

  return lines
}

function generateArray(type) {
  const instanceName = toSwiftInstanceName(type.name)
  const elementCodecInit = getSwiftCodecInit(type.type)

  const lines = []
  lines.push(`// ${type.fqn}`)
  lines.push(`public let ${instanceName} = Primitive.Array(${elementCodecInit})`)
  return lines
}

function generateRecord(type) {
  const instanceName = toSwiftInstanceName(type.name)
  const valueCodecInit = getSwiftCodecInit(type.value)

  const lines = []
  lines.push(`// ${type.fqn}`)
  lines.push(`public let ${instanceName} = Primitive.Record(${valueCodecInit})`)
  return lines
}

function generateStruct(struct) {
  const typeName = toSwiftTypeName(struct.name)
  const instanceName = toSwiftInstanceName(struct.name)
  const fields = struct.fields
  const flagsPosition = struct.flagsPosition
  const hasFlags = flagsPosition !== -1

  const shiftByField = new Map()
  for (const rf of struct.resolvedFields || []) {
    shiftByField.set(rf.field.name, rf.shift)
  }

  function fieldSwiftType(field) {
    if (isBoolField(field)) return 'Bool'
    const base = getSwiftType(field.type)
    if (field.array) return isOptionalField(field) ? `[${base}]?` : `[${base}]`
    return isOptionalField(field) ? `${base}?` : base
  }

  // _uint comes first (used for the flags word); bool fields need no codec
  const codecs = new Map()
  if (hasFlags) codecs.set('_uint', 'Primitive.UInt()')
  for (const field of fields) {
    if (isBoolField(field)) continue
    const varName = getFieldCodecVar(field)
    if (!codecs.has(varName)) {
      let init
      if (field.array) {
        init = 'Primitive.Array(' + getSwiftCodecInit(field.type) + ')'
      } else if (field.inline) {
        init = toSwiftTypeName(field.type.name) + 'InlineCodec()'
      } else {
        init = getSwiftCodecInit(field.type)
      }
      codecs.set(varName, init)
    }
  }

  const preEnd = hasFlags ? flagsPosition : fields.length

  const lines = []

  lines.push(`// ${struct.fqn}`)
  lines.push(`public struct ${typeName} {`)
  for (const field of fields) {
    lines.push(`  public var ${field.name}: ${fieldSwiftType(field)}`)
  }
  lines.push('')
  const initParams = fields.map((f) => {
    if (isBoolField(f)) return `${f.name}: Bool = false`
    if (isOptionalField(f)) return `${f.name}: ${fieldSwiftType(f)} = nil`
    return `${f.name}: ${fieldSwiftType(f)}`
  })
  lines.push(`  public init(${initParams.join(', ')}) {`)
  for (const field of fields) {
    lines.push(`    self.${field.name} = ${field.name}`)
  }
  lines.push('  }')
  lines.push('}')
  lines.push('')

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${typeName}`)
  lines.push('')
  for (const [varName, init] of codecs) {
    lines.push(`  let ${varName} = ${init}`)
  }
  lines.push('')
  lines.push(`  public init() {}`)
  lines.push('')

  lines.push(`  public func preencode(_ state: inout State, _ value: ${typeName}) {`)
  for (let i = 0; i < preEnd; i++) {
    lines.push(`    ${getFieldCodecVar(fields[i])}.preencode(&state, value.${fields[i].name})`)
  }
  if (hasFlags) {
    lines.push(`    var _flags: UInt = 0`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) lines.push(`    if value.${f.name} { _flags |= ${f.flag} }`)
      else if (isOptionalField(f))
        lines.push(`    if value.${f.name} != nil { _flags |= ${f.flag} }`)
    }
    lines.push(`    _uint.preencode(&state, _flags)`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) continue
      if (isOptionalField(f)) {
        lines.push(
          `    if let _v = value.${f.name} { ${getFieldCodecVar(f)}.preencode(&state, _v) }`
        )
      } else {
        lines.push(`    ${getFieldCodecVar(f)}.preencode(&state, value.${f.name})`)
      }
    }
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func encode(_ state: inout State, _ value: ${typeName}) throws {`)
  for (let i = 0; i < preEnd; i++) {
    lines.push(`    try ${getFieldCodecVar(fields[i])}.encode(&state, value.${fields[i].name})`)
  }
  if (hasFlags) {
    lines.push(`    var _flags: UInt = 0`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) lines.push(`    if value.${f.name} { _flags |= ${f.flag} }`)
      else if (isOptionalField(f))
        lines.push(`    if value.${f.name} != nil { _flags |= ${f.flag} }`)
    }
    lines.push(`    try _uint.encode(&state, _flags)`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) continue
      if (isOptionalField(f)) {
        lines.push(
          `    if let _v = value.${f.name} { try ${getFieldCodecVar(f)}.encode(&state, _v) }`
        )
      } else {
        lines.push(`    try ${getFieldCodecVar(f)}.encode(&state, value.${f.name})`)
      }
    }
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func decode(_ state: inout State) throws -> ${typeName} {`)
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`    let ${f.name} = try ${getFieldCodecVar(f)}.decode(&state)`)
  }
  if (hasFlags) {
    lines.push(`    let _flags = try _uint.decode(&state)`)
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) {
        lines.push(`    let ${f.name} = _flags & ${f.flag} != 0`)
      } else if (isOptionalField(f)) {
        if (f.inline) {
          const shift = shiftByField.get(f.name) || 0
          lines.push(
            `    let ${f.name}: ${fieldSwiftType(f)} = _flags & ${f.flag} != 0 ? try ${getFieldCodecVar(f)}.decode(&state, inlining: _flags >> ${shift}) : nil`
          )
        } else {
          lines.push(
            `    let ${f.name}: ${fieldSwiftType(f)} = _flags & ${f.flag} != 0 ? try ${getFieldCodecVar(f)}.decode(&state) : nil`
          )
        }
      } else {
        lines.push(`    let ${f.name} = try ${getFieldCodecVar(f)}.decode(&state)`)
      }
    }
  }
  lines.push(`    return ${typeName}(`)
  for (let i = 0; i < fields.length; i++) {
    const comma = i < fields.length - 1 ? ',' : ''
    lines.push(`      ${fields[i].name}: ${fields[i].name}${comma}`)
  }
  lines.push('    )')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push(`public let ${instanceName} = ${typeName}Codec()`)

  return lines
}

function generateInlineCodec(struct) {
  const typeName = toSwiftTypeName(struct.name)
  const instanceName = toSwiftInstanceName(struct.name) + 'Inline'
  const fields = struct.fields
  const flagsPosition = struct.flagsPosition
  const hasFlags = flagsPosition !== -1
  const preEnd = hasFlags ? flagsPosition : fields.length

  const codecs = new Map()
  for (const field of fields) {
    if (isBoolField(field)) continue
    const varName = getSwiftCodecVar(field.type)
    if (!codecs.has(varName)) {
      const init = field.array
        ? 'Primitive.Array(' + getSwiftCodecInit(field.type) + ')'
        : getSwiftCodecInit(field.type)
      codecs.set(varName, init)
    }
  }

  const lines = []
  lines.push(`// ${struct.fqn} (inline)`)
  lines.push(`public struct ${typeName}InlineCodec {`)
  for (const [varName, init] of codecs) {
    lines.push(`  let ${varName} = ${init}`)
  }
  lines.push('')

  lines.push(`  public func preencode(_ state: inout State, _ value: ${typeName}) {`)
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`    ${getSwiftCodecVar(f.type)}.preencode(&state, value.${f.name})`)
  }
  if (hasFlags) {
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) continue
      if (isOptionalField(f)) {
        lines.push(
          `    if let _v = value.${f.name} { ${getSwiftCodecVar(f.type)}.preencode(&state, _v) }`
        )
      } else {
        lines.push(`    ${getSwiftCodecVar(f.type)}.preencode(&state, value.${f.name})`)
      }
    }
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func encode(_ state: inout State, _ value: ${typeName}) throws {`)
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`    try ${getSwiftCodecVar(f.type)}.encode(&state, value.${f.name})`)
  }
  if (hasFlags) {
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) continue
      if (isOptionalField(f)) {
        lines.push(
          `    if let _v = value.${f.name} { try ${getSwiftCodecVar(f.type)}.encode(&state, _v) }`
        )
      } else {
        lines.push(`    try ${getSwiftCodecVar(f.type)}.encode(&state, value.${f.name})`)
      }
    }
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func decode(_ state: inout State, inlining: UInt) throws -> ${typeName} {`)
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`    let ${f.name} = try ${getSwiftCodecVar(f.type)}.decode(&state)`)
  }
  if (hasFlags) {
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (isBoolField(f)) {
        lines.push(`    let ${f.name} = inlining & ${f.flag} != 0`)
      } else if (isOptionalField(f)) {
        lines.push(
          `    let ${f.name}: ${getSwiftType(f.type)}? = inlining & ${f.flag} != 0 ? try ${getSwiftCodecVar(f.type)}.decode(&state) : nil`
        )
      } else {
        lines.push(`    let ${f.name} = try ${getSwiftCodecVar(f.type)}.decode(&state)`)
      }
    }
  }
  lines.push(`    return ${typeName}(`)
  for (let i = 0; i < fields.length; i++) {
    const comma = i < fields.length - 1 ? ',' : ''
    lines.push(`      ${fields[i].name}: ${fields[i].name}${comma}`)
  }
  lines.push('    )')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push(`public let ${instanceName} = ${typeName}InlineCodec()`)

  return lines
}
