name: Integrate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm test
  swift:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Swift / ${{ matrix.os }}
    steps:
      - uses: holepunchto/actions/node-base@v1
      - uses: swift-actions/setup-swift@v2
      - run: npm run test:swift
      - run: npm run test:cross-language
